ASITUS_THIRDPARTY_PRODUCT("vtk" "" "vtkAlgorithm.h" "vtkCommonCore")

add_definitions (-DUSE_VTK)

if (3RDPARTY_vtk_INCLUDE_DIR STREQUAL "")
  message (STATUS "... VTK Include dir is not conventional")
  list (REMOVE_ITEM 3RDPARTY_NOT_INCLUDED 3RDPARTY_vtk_INCLUDE_DIR)
  set (3RDPARTY_vtk_INCLUDE_DIR ${3RDPARTY_vtk_DIR}/include/vtk CACHE FILEPATH "Non-conventional inc dir" FORCE)
endif()

message (STATUS "... VTK Include dirs: ${3RDPARTY_vtk_INCLUDE_DIR}")
message (STATUS "... VTK Library dirs: ${3RDPARTY_vtk_LIBRARY_DIR}")
message (STATUS "... VTK Binary  dirs: ${3RDPARTY_vtk_DLL_DIR}")

string (REPLACE lib libd 3RDPARTY_vtk_LIBRARY_DIR_DEBUG ${3RDPARTY_vtk_LIBRARY_DIR})
if (3RDPARTY_vtk_LIBRARY_DIR_DEBUG AND EXISTS "${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}")
  if (WIN32)
    if (NOT EXISTS "${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}/vtkCommonCore.lib")
      set (3RDPARTY_vtk_LIBRARY_DIR_DEBUG "" CACHE INTERNAL "" FORCE)
    endif()
  else()
    if (NOT EXISTS "${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}/libvtkCommonCore.so")
      set (3RDPARTY_vtk_LIBRARY_DIR_DEBUG "" CACHE INTERNAL "" FORCE)
    endif()
  endif()
endif()

if (WIN32)
  string (REPLACE bin bind 3RDPARTY_vtk_DLL_DIR_DEBUG ${3RDPARTY_vtk_DLL_DIR})
  if (3RDPARTY_vtk_DLL_DIR_DEBUG AND EXISTS "${3RDPARTY_vtk_DLL_DIR_DEBUG}")
    if (NOT EXISTS "${3RDPARTY_vtk_DLL_DIR_DEBUG}/vtkCommonCore.dll")
      set (3RDPARTY_vtk_DLL_DIR_DEBUG "" CACHE INTERNAL "" FORCE)
    endif()
  endif()
endif()

message (STATUS "... VTK Debug Library dirs: ${3RDPARTY_vtk_LIBRARY_DIR_DEBUG}")
message (STATUS "... VTK Debug Binary  dirs: ${3RDPARTY_vtk_DLL_DIR_DEBUG}")

#--------------------------------------------------------------------------
# Installation
#--------------------------------------------------------------------------

if (NOT BUILD_ALGO_ONLY)
  if (WIN32)
    set (3RDPATY_INSTALL_DIR ${3RDPARTY_vtk_DLL_DIR})
    set (3RDPATY_INSTALL_DIR_DEBUG ${3RDPARTY_vtk_DLL_DIR}d)
    set (LIB_PREFIX "")
    set (LIB_SUFFIX ".dll")
  else()
    set (3RDPATY_INSTALL_DIR ${3RDPARTY_vtk_LIBRARY_DIR})
    set (3RDPATY_INSTALL_DIR_DEBUG ${3RDPARTY_vtk_LIBRARY_DIR})
    set (LIB_PREFIX "lib")
    set (LIB_SUFFIX ".so.1")
  endif()

  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkChartsCore${LIB_SUFFIX}                  CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonComputationalGeometry${LIB_SUFFIX} CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonColor${LIB_SUFFIX}                 CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonCore${LIB_SUFFIX}                  CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonDataModel${LIB_SUFFIX}             CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonExecutionModel${LIB_SUFFIX}        CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonMath${LIB_SUFFIX}                  CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonMisc${LIB_SUFFIX}                  CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonSystem${LIB_SUFFIX}                CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkCommonTransforms${LIB_SUFFIX}            CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersCore${LIB_SUFFIX}                 CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersExtraction${LIB_SUFFIX}           CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersGeneral${LIB_SUFFIX}              CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersGeometry${LIB_SUFFIX}             CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersHybrid${LIB_SUFFIX}               CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersImaging${LIB_SUFFIX}              CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersModeling${LIB_SUFFIX}             CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersParallel${LIB_SUFFIX}             CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersSources${LIB_SUFFIX}              CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkFiltersStatistics${LIB_SUFFIX}           CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkfreetype${LIB_SUFFIX}                    CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkGUISupportQt${LIB_SUFFIX}                CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkglew${LIB_SUFFIX}                        CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingColor${LIB_SUFFIX}                CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingCore${LIB_SUFFIX}                 CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingFourier${LIB_SUFFIX}              CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingGeneral${LIB_SUFFIX}              CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingHybrid${LIB_SUFFIX}               CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkImagingSources${LIB_SUFFIX}              CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkInteractionWidgets${LIB_SUFFIX}          CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkInteractionStyle${LIB_SUFFIX}            CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkInfovisCore${LIB_SUFFIX}                 CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkInfovisLayout${LIB_SUFFIX}               CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOCore${LIB_SUFFIX}                      CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOImage${LIB_SUFFIX}                     CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOLegacy${LIB_SUFFIX}                    CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOExport${LIB_SUFFIX}                    CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOXML${LIB_SUFFIX}                       CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOXMLParser${LIB_SUFFIX}                 CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkexpat${LIB_SUFFIX}                       CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkIOExportOpenGL2${LIB_SUFFIX}             CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkParallelCore${LIB_SUFFIX}                CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingAnnotation${LIB_SUFFIX}         CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingContext2D${LIB_SUFFIX}          CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingContextOpenGL2${LIB_SUFFIX}     CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingCore${LIB_SUFFIX}               CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingGL2PSOpenGL2${LIB_SUFFIX}       CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingFreeType${LIB_SUFFIX}           CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingLabel${LIB_SUFFIX}              CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingOpenGL2${LIB_SUFFIX}            CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkRenderingVolume${LIB_SUFFIX}             CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtksys${LIB_SUFFIX}                         CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkViewsContext2D${LIB_SUFFIX}              CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkViewsCore${LIB_SUFFIX}                   CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkViewsInfovis${LIB_SUFFIX}                CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkzlib${LIB_SUFFIX}                        CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtklz4${LIB_SUFFIX}                         CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkgl2ps${LIB_SUFFIX}                       CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkpng${LIB_SUFFIX}                         CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtklibharu${LIB_SUFFIX}                     CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkDICOMParser${LIB_SUFFIX}                 CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkmetaio${LIB_SUFFIX}                      CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtktiff${LIB_SUFFIX}                        CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkjpeg${LIB_SUFFIX}                        CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtklzma${LIB_SUFFIX}                        CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR}/${LIB_PREFIX}vtkdoubleconversion${LIB_SUFFIX}            CONFIGURATIONS Release RelWithDebInfo DESTINATION bin)

  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkChartsCore${LIB_SUFFIX}                  CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkCommonComputationalGeometry${LIB_SUFFIX} CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkCommonColor${LIB_SUFFIX}                 CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkCommonCore${LIB_SUFFIX}                  CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkCommonDataModel${LIB_SUFFIX}             CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkCommonExecutionModel${LIB_SUFFIX}        CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkCommonMath${LIB_SUFFIX}                  CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkCommonMisc${LIB_SUFFIX}                  CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkCommonSystem${LIB_SUFFIX}                CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkCommonTransforms${LIB_SUFFIX}            CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersCore${LIB_SUFFIX}                 CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersExtraction${LIB_SUFFIX}           CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersGeneral${LIB_SUFFIX}              CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersGeometry${LIB_SUFFIX}             CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersHybrid${LIB_SUFFIX}               CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersImaging${LIB_SUFFIX}              CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersModeling${LIB_SUFFIX}             CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersParallel${LIB_SUFFIX}             CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersSources${LIB_SUFFIX}              CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkFiltersStatistics${LIB_SUFFIX}           CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkfreetype${LIB_SUFFIX}                    CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkGUISupportQt${LIB_SUFFIX}                CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkglew${LIB_SUFFIX}                        CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkImagingColor${LIB_SUFFIX}                CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkImagingCore${LIB_SUFFIX}                 CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkImagingFourier${LIB_SUFFIX}              CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkImagingGeneral${LIB_SUFFIX}              CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkImagingHybrid${LIB_SUFFIX}               CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkImagingSources${LIB_SUFFIX}              CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkInteractionWidgets${LIB_SUFFIX}          CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkInteractionStyle${LIB_SUFFIX}            CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkInfovisCore${LIB_SUFFIX}                 CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkInfovisLayout${LIB_SUFFIX}               CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkIOCore${LIB_SUFFIX}                      CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkIOImage${LIB_SUFFIX}                     CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkIOLegacy${LIB_SUFFIX}                    CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkIOExport${LIB_SUFFIX}                    CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkIOXML${LIB_SUFFIX}                       CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkIOXMLParser${LIB_SUFFIX}                 CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkexpat${LIB_SUFFIX}                       CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkIOExportOpenGL2${LIB_SUFFIX}             CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkParallelCore${LIB_SUFFIX}                CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkRenderingAnnotation${LIB_SUFFIX}         CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkRenderingContext2D${LIB_SUFFIX}          CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkRenderingContextOpenGL2${LIB_SUFFIX}     CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkRenderingCore${LIB_SUFFIX}               CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkRenderingGL2PSOpenGL2${LIB_SUFFIX}       CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkRenderingFreeType${LIB_SUFFIX}           CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkRenderingLabel${LIB_SUFFIX}              CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkRenderingOpenGL2${LIB_SUFFIX}            CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkRenderingVolume${LIB_SUFFIX}             CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtksys${LIB_SUFFIX}                         CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkViewsContext2D${LIB_SUFFIX}              CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkViewsCore${LIB_SUFFIX}                   CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkViewsInfovis${LIB_SUFFIX}                CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkzlib${LIB_SUFFIX}                        CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtklz4${LIB_SUFFIX}                         CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkgl2ps${LIB_SUFFIX}                       CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkpng${LIB_SUFFIX}                         CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtklibharu${LIB_SUFFIX}                     CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkDICOMParser${LIB_SUFFIX}                 CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkmetaio${LIB_SUFFIX}                      CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtktiff${LIB_SUFFIX}                        CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkjpeg${LIB_SUFFIX}                        CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtklzma${LIB_SUFFIX}                        CONFIGURATIONS Debug DESTINATION bin)
  install (FILES ${3RDPATY_INSTALL_DIR_DEBUG}/${LIB_PREFIX}vtkdoubleconversion${LIB_SUFFIX}            CONFIGURATIONS Debug DESTINATION bin)
endif()
